# render.yaml - FINAL DOCKER VERSION

services:
  # 1. Redis Cache
  - type: redis
    name: claimcheck-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all internal

  # 2. Backend (API + Worker COMBINED) using Docker
  - type: web
    name: claimcheck-api
    plan: free
    runtime: docker
    # This points to your Dockerfile in the Backend directory
    dockerfilePath: ./Backend/Dockerfile
    # The health check is still useful
    healthCheckPath: /api/health
    envVars:
      - fromGroup: ClaimCheck Shared Secrets
      - key: REDIS_URL
        fromService:
          type: redis
          name: claimcheck-redis
          property: connectionString
      - key: PORT
        value: 10000

  # 3. Frontend
  - type: web
    name: claimcheck-web
    runtime: static
    rootDir: Frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        # This should be the final public URL of your API service
        value: https://claimcheck-api.onrender.com
      - fromGroup: ClaimCheck Shared Secrets