services:
  # Redis Cache
  - type: redis
    name: claimcheck-redis
    plan: free
    maxmemoryPolicy: allkeys-lru

  # Backend API Server
  - type: web
    name: claimcheck-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node server.js"
    healthCheckPath: /api/health 
    envVars:
      - fromGroup: ClaimCheck Shared Secrets

  # Backend Worker
  - type: worker
    name: claimcheck-worker
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "node worker.js"
    envVars:
      - fromGroup: ClaimCheck Shared Secrets

  # Frontend Static Site
  - type: web
    name: claimcheck-web
    runtime: static
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: claimcheck-api
          property: url
      - key: VITE_CLOUDINARY_CLOUD_NAME
        fromGroup: ClaimCheck Shared Secrets